# Site settings
# in the templates available like {{ site.myvariable }}.
title: 
email: 
brand: 羊咩咩的猫舍
headline: 吃吃吃，睡睡睡，买买买
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 kauchy All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +xxxxxx

# Tracking
googleAnalitycsID: UA-83933844-1

